# Generated by Django 4.2.1 on 2023-05-25 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("transaction_id", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_history",
                    models.ManyToManyField(blank=True, to="accounts.accounthistory"),
                ),
            ],
        ),
    ]
