# Generated by Django 4.2.1 on 2023-05-25 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounthistory",
            name="id",
        ),
        migrations.AlterField(
            model_name="accounthistory",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
