# Generated by Django 4.2.1 on 2023-05-25 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_accounthistory_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="customer_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
