# Generated by Django 4.2.1 on 2023-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="customer_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
