# Generated by Django 4.2.1 on 2023-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_balance_alter_account_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
