# Generated by Django 4.2.1 on 2023-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        ("accounts", "0007_transaction_delete_accounthistory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.AlterField(
            model_name="account",
            name="transaction_history",
            field=models.ManyToManyField(blank=True, to="transactions.transaction"),
        ),
    ]
