# Generated by Django 4.2.1 on 2023-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customusers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="accounts",
        ),
        migrations.AddField(
            model_name="customuser",
            name="customer_id",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
