# Generated by Django 4.2.1 on 2023-05-25 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("account_id", models.CharField(default="", max_length=100)),
                ("reciever_id", models.CharField(default="", max_length=100)),
                ("time", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
