# Generated by Django 4.2.1 on 2023-05-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_amount_alter_transaction_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="reciever_id",
            new_name="receiver_id",
        ),
    ]
