# Generated by Django 4.2.1 on 2023-05-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_reciever_id_transaction_receiver_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-time"]},
        ),
    ]
